name = "Browse"
license = "GPLv2"
licenselink = "https://github.com/onweru/browse/blob/master/LICENSE.md"
description = "Browse is a responsive, clean and content-focused Hugo theme."
homepage = "https://github.com/onweru/browse/"
demosite = "https://browse.neuralvibes.com/"
tags = ["blog", "responsive", "multilingual", "rss", "darkmode"]
features = ["blog", "responsive", "multilingual", "rss", "darkmode"]
min_version = "0.85"

[[authors]]
  name = "Dan Weru"
  homepage = "https://neuralvibes.com/author/"
[[authors]]
  name = "Andrew Hoog"
  homepage = "https://www.nowsecure.com/"
[[authors]]
  name = "Vimux"
  homepage = "https://github.com/Vimux"

# If porting an existing theme
[original]
  name = "Mainroad Hugo Theme"
  homepage = "https://github.com/Vimux/Mainroad"
  repo = "https://github.com/Vimux/Mainroad"
